post http://localhost:8800/auth/login
Content-Type: application/json

{
    "phoneNumber" : "9952050503"
}

###
post http://localhost:8800/auth/verify-otp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6Ijk5NTIwNTA1MDMiLCJpYXQiOjE2MzA5OTY0MjgsImV4cCI6MTYzMDk5NzQyOH0.KItLdsuSHW9A07vPUfuHe66AsF6afIJnS_4yzN1TIX8

{
    "phoneNumber" : "9952050503",
    "otp" : "2172"
}

###
get http://localhost:8800/auth/new-token?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6Ijk5NTIwNTA1MDMiLCJpYXQiOjE2MzEwMzYyNjksImV4cCI6MTYzMTAzNjI5OX0.4wNHd7yJwIXTLxID9nH6snpXqiR_ltK_sdAHKkFTqkI

###

get http://localhost:8800/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6Ijk5NTIwNTA1MDMiLCJpYXQiOjE2MzEwMzcwNTIsImV4cCI6MTYzMTAzODA1Mn0.5jxnWD1TUGNWoSTnbu4NUVekSZ_g47_ZyYNYRnWRnbw

###

get http://localhost:8800/user/9952050503
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6Ijk5NTIwNTA1MDMiLCJpYXQiOjE2MzEwMzcwNTIsImV4cCI6MTYzMTAzODA1Mn0.5jxnWD1TUGNWoSTnbu4NUVekSZ_g47_ZyYNYRnWRnbw
